### ISSUE TITLE
Deploying of Java Web Application with Database

### ISSUE THREAD

**Issue by JaynitAnand** [shashirajraja/onlinebookstore#10]
Can you please tell how to deploy java web application with database on github?
And also which database you are using?

**Comment by shashirajraja** [comment]
You can run or deploy this demo project on tomcat server by using the eclipse ide. Here we are using the MySql database, and for demo you can use the table script given [Here](https://github.com/shashirajraja/onlinebookstore/blob/gh-pages/Dummy_Database.md).
