### ISSUE TITLE
Facing internal errors like "HTTP Status 500, 404"

### ISSUE THREAD

**Issue by Rakshit005** [shashirajraja/onlinebookstore#17]
hello
I tried to run the project on my laptop in the same way as your procedure in the readme file.
The java, tomcat, MySQL connections are smooth and stable but whenever I try to run the project,
Firstly it will show the home page correctly.
But when I try to do admin login or user login or see available books, it gives me errors like 
" HTTP STATUS 404 - The origin server did not find a current representation for the target resource or is not willing to disclose that one exists."
Is there any update to the content or any other thing, I tried general solutions available on the Net, but nothing worked.
Can you please tell me the solution?

@shashirajraja #

**Comment by Rakshit005** [comment]
Can you send me any short video of its working. I need this project for my college report. Backend code is not necessary. Just a video of its working.
Please 🙏
________________________________

**Comment by shashirajraja** [comment]
@Rakshit005 https://j2eebookstore.herokuapp.com/
