### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [shashirajraja/onlinebookstore#18]
Hey there!

I belong to an open source security research community, and a member (@s54r) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by shashirajraja** [comment]
Hi Jamie, 

Thank you for the above information, will look into it.

**Comment by JamieSlome** [comment]
@shashirajraja - thanks for the update 👍 

You can view the report directly here:
https://huntr.dev/bounties/3b7bb3c0-3a41-4953-8b7b-804f565aa702/

It is private and only accessible to you :)

**Comment by shashirajraja** [comment]
Sure, Thanks
