### ISSUE TITLE
HTTP STATUS 500- INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by manideep-yellani** [shashirajraja/onlinebookstore#22]
![85a110dd-28b0-406b-96a7-1343e6d11f0f](https://user-images.githubusercontent.com/95612168/165113439-1dbea027-64c7-41c5-99e0-6746ce7a2242.jpg)
its showing us this error:
TYPE: EXCEPTION REPORT
MESSAGE: ERROR INSTALLING SERVLET CLASS
DESCRIPTION:THE SERVER ENCOUNTERED AN UNEXPECTED CONFITION THAT PREVENTED IT FROM FULFILLING THE REQUEST
 error instantiating servlet class
![WhatsApp Image 2022-04-25 at 6 32 06 PM](https://user-images.githubusercontent.com/95612168/165114072-b520498d-b74c-4bd9-adea-2a4d1d4b3330.jpeg)

**Comment by manideep-yellani** [comment]
could you please respond soon and give us a solution for this, we tried it many times but just couldn't figure out why its happening. is it cause we imported the project and tried to run it? we did as the instructions said but we got this 500 internal server error
![WhatsApp Image 2022-04-25 at 6 32 06 PM](https://user-images.githubusercontent.com/95612168/165114819-b642a299-f9f0-4fcc-89e2-e5c00fea5b92.jpeg)
would appreciate a detailed cause for this problem and its solution
thanks in advance

**Comment by shashirajraja** [comment]
Hi there, this seems to be a problem with your lib files in Tomcat.Please
verify your server lib files to ensure that the JAR is there for resolving
the class.


Thanks and Regards
Shashi Raj

**Comment by shashirajraja** [comment]
Closing the issue, as no response from long time.
You can use the demo live url to see this project: https://j2eebookstore.herokuapp.com/
