### ISSUE TITLE
Getting white screen 

### ISSUE THREAD

**Issue by DivyaChandrayan** [shashirajraja/onlinebookstore#23]
I am getting white screen whenever I click on servlet pages like books available and admin login 
![image](https://user-images.githubusercontent.com/64527723/166693993-f29859a3-45e6-43de-b27b-30d58c9f2878.png)

**Comment by shashirajraja** [comment]
Please attach the console logs from eclipse also, so that i can help with the issue.

**Comment by shashirajraja** [comment]
Hi Divya,

Can you please attach the error logs also from your eclipse console, so
that i can help you.

Thanks & Regards
Shashi Raj

**Comment by shashirajraja** [comment]
This can be database connection issue, either SQL is not installed or the db properties are not configured correctly.
Closing this issue as didn't received response in long time.
