### ISSUE TITLE
Create application with REST API + Hibernate

### ISSUE THREAD

**Issue by ajay109458** [shashirajraja/onlinebookstore#3]
@shashirajraja 

Since nowadays servlets are being used very less at the industry level. But I appreciate your effort in creating the project. 

I have created a REST API application for your online store application.  Used HIbernate instead of JDBC behind the scene.
Refer - [Book Store App](https://github.com/ajay109458/BookStoreApp)

I hope it will be great learning for you.

**Comment by shashirajraja** [comment]
I understand your concern, but this was the demo project basically made for understanding the workflow of J2EE.
