### ISSUE TITLE
Add more books in the list

### ISSUE THREAD

**Issue by zugzwang03** [shashirajraja/onlinebookstore#42]
I want to add more books to the list as it is a library.
Can I make this contribution under hacktoberfest'22?

**Comment by shashirajraja** [comment]
Sure, you can go ahead with that, You can remove the dummy book details and update the sql queries at all places with actual book details like book name, author name, price, etc

**Comment by zugzwang03** [comment]
I am extremely sorry, but presently I can not manage time to dive into SQL. Would be glad if the issue is offered to someone skilled at it.

**Comment by shashirajraja** [comment]
No issue @zugzwang03 , someone else will look into these issues

**Comment by zugzwang03** [comment]
Thanks for understanding 😃

**Comment by sohailg** [comment]
i would like to take part into it. Help me with the process.
