### ISSUE TITLE
the button is not styled 

### ISSUE THREAD

**Issue by guneshmunjal** [shashirajraja/onlinebookstore#64]
this button should be styled accordingly with the website 

kindly assign me this under hactoberfest 

![Capture 13](https://user-images.githubusercontent.com/96971457/196020192-802337c7-ceed-4fe5-b1aa-eead7f473780.PNG)

**Comment by pooranjoyb** [comment]
Hey @shashirajraja , would be glad if you assign this to me!
Please add Hacktoberfest label while assigning :)

**Comment by ABHAY-Y** [comment]
Hello Sir, can you assign this task to me?

**Comment by guneshmunjal** [comment]
Sir kindly assign this under hactoberfest and add the label as well. 
Thank you sir.

**Comment by pooranjoyb** [comment]
@shahshirajraja Hello, sir, should I continue working on this and post a pull request for the changes or you want this to be as it is.
Asking because the issue #64 that you assigned me is closed now.
