### ISSUE TITLE
I can change the look and feel of the website

### ISSUE THREAD

**Issue by rajput999** [shashirajraja/onlinebookstore#73]
you can see my [website](https://rajput999.github.io/repo-2/). I can make it look something like this.

**Comment by rajput999** [comment]
I can make the footer for this.

**Comment by rajput999** [comment]
Hello @shashirajraja can you pls assign this work to me

**Comment by shashirajraja** [comment]
Please raise the issue again with appropriate context and better description about what exactly you would like to improve.
