### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by rajput999** [shashirajraja/onlinebookstore#85]
### Detailed description

Header is very important part of website soo a can make the header for the website and that will match the design of the website

### Context

Header is very important part of website without header website is incomplete.
header will make the website better.

### Additional information

you can see my website [website](https://rajput999.github.io/repo-2/)

**Comment by rajput999** [comment]
Can you pls give hacktoberfest label

**Comment by shashirajraja** [comment]
@rajput999 that label is not compulsory for issues

**Comment by rajput999** [comment]
Then how can it be count in hacktoberfest

**Comment by shashirajraja** [comment]
@rajput999 this repository itself is tagged with this label, so any PR will be counted.

**Comment by rajput999** [comment]
Hello @shashirajraja i Created the Header and also given logo to the website. Pls merge my pull request. and i also given hover effects.
<img width="1440" alt="Screenshot 2022-10-20 at 11 35 27 AM" src="https://user-images.githubusercontent.com/108625391/196872009-4494d40e-372d-4c92-bef5-68f9c70831bb.png">
